### ISSUE TITLE
documentation should be clear about installing python first

### ISSUE THREAD

**Issue by keremkoseoglu** [keremkoseoglu/Jira2Notion#1]

**Comment by CodeSadhu** [comment]
If nobody's assigned, I can do this.

**Comment by keremkoseoglu** [comment]
Sure @CodeSadhu ; what I had in mind is to simply update readme.md . Feel free to contribute! I'm waiting for your pull request. If you need anything else, let me know!

**Comment by CodeSadhu** [comment]
@keremkoseoglu Your project says it's Mac-specific. So just to be clear, you want to add instructions to install Python for Macs beforehand, right?

**Comment by keremkoseoglu** [comment]
Done by @CodeSadhu , many thanks!
