### ISSUE TITLE
Follow Notion API

### ISSUE THREAD

**Issue by keremkoseoglu** [keremkoseoglu/Jira2Notion#10]
When Notion API is released, we can use it instead of the 3rd party API.

**Comment by moam87moodi** [comment]
Get in iPhone6 iOS 12.5

**Comment by keremkoseoglu** [comment]
@moam87moodi I didn't understand what yo mean.

**Comment by keremkoseoglu** [comment]
Applied to Notion API beta program, waiting for acceptance.

**Comment by keremkoseoglu** [comment]
Notion API beta active, success in Postman, will implement to Python.
